name: Windows RDP
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin Aa123456!
    - name: Start NGROK Tunnel
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH
        Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
      env:
        NGROK_AUTH: ${{ secrets.NGROK_AUTH }}
    - name: Display RDP Address
      run: |
        Write-Host "Go to https://dashboard.ngrok.com/endpoints to get your RDP address"
